kind: Pod
apiVersion: v1
metadata:
  name: myvolconfig

spec:
  containers:
    - name: c1
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-akshay; sleep 5; done" ]
      volumeMounts:
       - name: testconfigmap
         mountPath: /tmp/config


  volumes:
    - name: testconfigmap
      configMap:
        name: mymap
        items:
           - key: samplefile
             path: samplefile

